### PR TITLE
add gitpod button and darklight theme reference

### PR DESCRIPTION
**Pull request by dpolivaev**

### CODE REVIEW

**Comment by macmarrum** [comment]
@dpolivaev The content I had created  in `README.md` was removed by you without a discussion. I would like to be consulted first, i.e. a PR to be open for a reasonable number of days until I opine.

Let's do this retrospectively. Could you please state your reasons for wanting to remove lines 5 to 14 from `README.md`?

**Comment by dpolivaev** [comment]
@macmarrum I restored the mentioned lines so we can discuss the reasons and the changes when we have time.
Generally, feel free to revert any of my changes until we have a discussion if you disagree.

I removed the text because I found it out-of-date and confusing:

> The main site is `Docs`, with `Attic` as a sub-directory.

I do not see any directory called "Docs" and I am confused about it

> `Attic` contains MediaWiki pages (pre-2022 wiki) migrated to Markdown for GitHub.

Actually, Attic contains two subdirectories called `new-wiki-initiative` and `old-mediawiki-content`

> The vision is to bring all MediaWiki content from `Attic` to `Docs`.

Makes no sense to me because `Attic` is a sub-directory, `Docs` is not a directory and we are not going to move all content, just some parts of it. And so on.

So I was so confused that I removed the lines. Now they are restored but I see some urgency in replacing them with something I can understand myself.

**Comment by macmarrum** [comment]
@dpolivaev I see your points. Yet, I prefer the approach to first discuss then merge; it's consistent with the general PR idea / flow.

> I removed the text because I found it out-of-date and confusing:
>> The main site is Docs, with Attic as a sub-directory.

> I do not see any directory called "Docs" and I am confused about it 

At the time when there were 2 separate docsify sites, it made sense: the main one was `Docs`, and the draft-documents site was `Attic`. Now that there's a single docsify site, i.e. after `Attic` has been merged into `Docs` as a sub-directory, it's less obvious.

Still, `Attic` contains content that needs some work before it can be moved to the main part of the house, formerly known as `Docs`. README.md was written before `Attic` got segregated into `new-wiki-initiative` and `old-mediawiki-content` sub-directories. It makes sense to me for README to reflect the new structure.

> Makes no sense to me because `Attic` is a sub-directory, `Docs` is not a directory 

`Docs` is the root directory. Please feel free to propose a good name to refer to it.

> and we are not going to move all content, just some parts of it. And so on.

What parts (kind of content) do you envision should be brought from `Attic` to main (`Docs`)?

**Comment by dpolivaev** [comment]
> Yet, I prefer the approach to first discuss then merge; it's consistent with the general PR idea / flow.

I am afraid that I prefer the approach merge and revert if necessary. I agreed to use the PR so that the changes can be discussed. I don't want to wait for anyone's approval unless I don't feel myself.

Therefore feel free to revert any changes using a new commit (no push force) and please don't insist on reviewing and discussing before merge. Anything else would produce too much delay and hassle.

**Comment by dpolivaev** [comment]
I am going to come back to the discussion later today

**Comment by dpolivaev** [comment]
> Still, Attic contains content that needs some work before it can be moved to the main part of the house, formerly known as Docs. README.md was written before Attic got segregated into new-wiki-initiative and old-mediawiki-content sub-directories. It makes sense to me for README to reflect the new structure.

Agreed

> Docs is the root directory. Please feel free to propose a good name to refer to it.

we could either call it the root directory as you just did or create a new directory "docs" and configure github pages to use it as a served content root. What do you like more?

> What parts (kind of content) do you envision should be brought from Attic to main (Docs)?

I don't know because I am not going to do it alone. In our last Freeplane user conference I suggested having an ensemble programming session which I could facilitate for improving the scripting documentation. Here I just suggested writing "some pages" instead of "all pages". 

How can we two continue with the readme?

**Comment by macmarrum** [comment]
> I am afraid that I prefer the approach merge and revert if necessary. 

Will you agree to this approach for the freeplane java repository?

**Comment by dpolivaev** [comment]
It depends on a concrete case.

**Comment by dpolivaev** [comment]
Regarding freeplane-docs, I think we need to meet online to better understand each other's concerns and find a solution that fits everyone.

**Comment by macmarrum** [comment]
Let me summarize. In case of freeplane/docs, you "prefer the approach merge and revert if necessary" and you "don't want to wait for anyone's approval unless [you] don't feel sure [yourself]". In your opinion "anything else would produce too much delay and hassle".

When it comes to freeplane/freplane (java), you are not so sure about such an approach. Therefore it tells me that the approach is not always the one you would choose.

I wonder what is so urgent about creating documentation in your opinion, that you'd like to avoid too much delay – could you please explain?
As for the hassle part, I believe it's polite to give others a chance to comment when there are changes to the content that they created. Only if there is no comment after an agreed number of days, the PR could be merged.

If we adopt the approach to merge first, the burden is on the original author: to monitor whether their content was modified. Whereas with the regular PR flow, the burden is on the author of changes: to find out who contributed the original content and ask for their opinion.

I am fine with having a voice call with you. I am away on holidays with bad or no internet; I will let you know my availability after I'm back.

**Comment by dpolivaev** [comment]
It looks like we have different scenarios and different concerns in minds. We can try to clarify them in chat, but I think that a call would be more effective.

**Comment by dpolivaev** [comment]
My assumption is that most contributors are contributing from time to time and that they are not likely to will to be responsible for future changes. All changes happen sequentially, all improvements are gradual, there is no "code ownership" or "document ownership", and the culture is change-friendly and experiment-friendly. Most changes do not require discussion, and in cases a discussion is wished the people are either available or not. If there is any disagreement, people need to come together to find a solution, but if they are not available, they have no voice. If you want to talk about differences and criteria for the code development we can do it during a call, but I can tell that neither in projects I do at work nor in Freeplane there is any form of code ownership.

**Comment by macmarrum** [comment]
Thank you for your explanations.

>> Docs is the root directory. Please feel free to propose a good name to refer to it.

> we could either call it the root directory as you just did or create a new directory "docs" and configure github pages to use it as a served content root. What do you like more?

The content is already served at **docs**.freeplane.org and the code available at github.com/freeplane/**docs**. Adding another `docs` would be superfluous.

Let's call it `docs root` or simply `root`.

> It looks like we have different scenarios and different concerns in minds. We can try to clarify them in chat, but I think that a call would be more effective.

I can only do Conversation (chat) until I'm back from my travels. I believe it is quite effective to record thoughts/opinions in writing. It gives a chance to ponder the other's opinions, think about one's own and provide counter arguments. And I am fine with spending some time and effort as we discuss about the rules of cooperation, because they are important to me. I would like to continue the written discussion, if you would be so kind and provide answers/opinions regarding the points/questions I raised:

1. What is your vision for `attic` content? When you say "some pages", what is the outcome you'd like to achieve? In my opinion the vision is to bring all content from `attic` to `docs root`. And the outcome to be achieved is to have each page reviewed/completed before incorporating it to `docs root` and/or removing it from `attic` as no longer relevant.
3. What is so urgent about creating documentation, in your opinion, that you'd like to avoid too much delay? I see little reason for urgency.
4. Why would it be a hassle, in your opinion, to apply the standard PR procedure of waiting for feedback if the changes are affecting content created by others? I believe it's polite to give others a chance to comment when there are changes to the content that they created. Only if there is no comment after an agreed number of days, the PR could be merged.
5. What are the reasons you wouldn't go for the merge-first approach in the freeplane/freeplane (java) repository?

**Comment by macmarrum** [comment]
And now for something completely different.

I wonder what is the objective for having
```markdown
## Edit on-line

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/freeplane/docs)
```

I know that when I click the button, it opens an ephemeral workspace on GitPod, based on github.com/freeplane/docs. Since the repo is not my own fork, I wouldn't make changes in there.

**Comment by dpolivaev** [comment]
> The content is already served at docs.freeplane.org and the code available at github.com/freeplane/docs. Adding another docs would be superfluous.

Subdomain and repository names are voluntary and can not be used in the context of the folder name.

> Let's call it docs root or simply root.

Agreed

> What is your vision for attic content? When you say "some pages", what is the outcome you'd like to achieve? In my opinion the vision is to bring all content from attic to docs root. And the outcome to be achieved is to have each page reviewed/completed before incorporating it to docs root and/or removing it from attic as no longer relevant.

Yes, if all attic pages get moved or removed nothing would left. However, saying that all pages should be moved and not mentioning options to remove or merge them seems to be not accurate enough to me.

> What is so urgent about creating documentation, in your opinion, that you'd like to avoid too much delay? I see little reason for urgency.

I don't like waiting for responses uncertain time long and generally try to avoid uncertainty as much as a can. I want to avoid blocking the progress and waiting for the other person. It would just make everyone angry and unmotivated, the person who is waiting and the person who is pressed to respond. In quite many professional projects reviews become a stopper for development. I want to avoid it at least in the documentation project. I want to keep moving and avoid friction.

> Why would it be a hassle, in your opinion, to apply the standard PR procedure of waiting for feedback if the changes are affecting content created by others? I believe it's polite to give others a chance to comment when there are changes to the content that they created. Only if there is no comment after an agreed number of days, the PR could be merged.

Why should removing obviously wrong or inaccurate descriptions or making minor changes and experiments be put on hold again and again? It does not make any sense to me.

> What are the reasons you wouldn't go for the merge-first approach in the freeplane/freeplane (java) repository?

It depends on the amount and kind of changes. For example, translations are merged without reviewing, and limited scope contributions and fixes made by authorized contributors can be merged without reviewing. We need always consider keeping the flow on the one side and maintaining the quality on the other side, and different cases are treated differently.

For example, look at the recent commits of Felix Natter:

https://github.com/freeplane/freeplane/search?o=desc&q=author%3Afnatter&s=committer-date&type=commits

Also, if I want to add a gitpod button I do not want to have to get anyone's approval. I do not mind having a discussion later but I do not want to be blocked. Everyone wants to make progress, to push, and not to stay in a way.

> I wonder what is the objective for having Open in Gitpod. I know that when I click the button, it opens an ephemeral workspace on GitPod, based on github.com/freeplane/docs. Since the repo is not my own fork, I wouldn't make changes in there.

GitPod integration is used by quite many really known projects like https://github.com/assertj/assertj-core. However they use the special URL https://gitpod.io/from-referrer/ instead of hard coded project. I can make this change. Done / merged.

I would like to conclude with a very general statement.

There are certainly different styles of introducing improvement. It is always a process consisting of many steps. And  we always have a choice between blocking changes if we do not like something in them or changing the changes trying to understand and improve the part contributed by the others. And I really hope that we find a non-blocking way of collaboration on the freeplane docs project.

**Comment by macmarrum** [comment]
Thanks for responding.

I agree that when introducing new content, no PR review should be required.

I strongly believe that when content is changed, the original authors should be given a chance to comment. This is normally done via PR, where the people are asked to comment. I propose to time-box it to 7 days; if no comment, merge the PR.

We also know that some past contributors can no longer be identified or aren't active anymore, like quickfold. For content created by them, no PR review would be needed.

I believe with this approach we meet in the middle between what you want and what I want.
What do you think?

**Comment by dpolivaev** [comment]
> I strongly believe that when content is changed, the original authors should be given a chance to comment. This is normally done via PR, where the people are asked to comment. I propose to time-box it to 7 days; if no comment, merge the PR.

Everyone can always comment everything. Why do you want to wait 7days?
Also, why do you want to give the original author any extra rights?

**Comment by macmarrum** [comment]
When I create content, I do the effort of thinking it through. I spend time and energy with the thought that something good is being created. I would be sad to see someone else come and destroy it. I would like to have a chance of explaining my idea and working with the next contributor to expand it together.

> why do you want to give the original author any extra rights?

Because the original author had the courage and creative insight to produce something new, something that no-one else created.
To be clear, once changes are introduced by someone else, the author list expands and I expect the third person to inquire comments from both of the authors whose content is being changed.

> Everyone can always comment everything. Why do you want to wait 7days?

7 days is a reasonable number of days in my opinion. People have their own lives. Creating Freeplane documentation is an after-hours voluntary activity, not a day job. I don't expect people to have time every day but I think once a week is a reasonable expectation.

I have given my opinion. I would like to read yours on the subjects that you asked about:
1. How many days is a reasonable number to wait and why?
2. Why the one who changes content should have more rights than the original author?

**Comment by dpolivaev** [comment]
> When I create content, I do the effort of thinking it through. I spend time and energy with the thought that something good is being created. I would be sad to see someone else come and destroy it.

Nobody comes to intentionally destroy your work. Every trustworthy person always tries to contribute their best. Neither the documentation of Freeplane nor the code of Freeplane is supposed to be a product of a single author. Otherwise it would be not open but closed source with a copyright. If you wrote a book or a piece of art it would be something different. 

> How many days is a reasonable number to wait and why?

Zero. Because we are agile and react to ideas as they come. If you have good arguments, it is never too late to consider them.
But waiting and strict rules can be poison for encouragement.

> Why the one who changes content should have more rights than the original author?

The ones changing the content have just the same. The original author can always suggest any changes and share any concerns. Being a Contributor does not mean having the right to slow down the process.

I do not know who created the readme file and it is even not interesting. Then I added the GitPod button. Then you mentioned that you want it to work also from the forked repositories. Then I found out how to implement it using special URL https://gitpod.io/from-referrer/. It was a nice flow. And had you delivered you concern two weeks later I would probably do the same.

> People have their own lives. Creating Freeplane documentation is an after-hours voluntary activity, not a day job. I don't expect people to have time every day but I think once a week is a reasonable expectation.

Yes, and therefore we need a process where people can be productive without blockers, without any waiting times.

Let us assume there was a PR and you reacted some days later and the PR author reacted some more days later. It means that development would stop, and no productive work would possible because of the waiting times.

**Comment by macmarrum** [comment]
Thank you for your explanations. I have a different opinion and at this time cannot support the proposed flow of work. I will step aside and let you guys work on the documentation.

**Comment by dpolivaev** [comment]
I have described my beliefs. Having this discussion here as a pull request discussion has left the community and other contributors behind. If we had this discussion in a proper place another opinion could have influenced it.
But if you feel like you do not want to contribute because of the workflow I have to accept it.

If you don't mind I would like to write a discussion post with a reference to our discussion here just to get other opinions.

**Comment by macmarrum** [comment]
Fine with me.
I know that it isn't so easy to monitor PRs, as I mentioned [earlier](https://github.com/freeplane/docs/pull/59#issuecomment-1193386755). I am glad you understand that.

**Comment by dpolivaev** [comment]
> I have a different opinion and at this time cannot support the proposed flow of work. 

I have been thinking about your conclusion and I do not understand what is so important to you that you prefer stepping aside to having all freedoms and opportunities. Which one do you miss?

Currently there is one open PR from 1-Dimensional-Box and some closed PRs.
The open PR is reviewed by nobody because nobody feels responsible and I think it is just the normality.
However for reviewing any PR it does not matter if it has already been merged or not given its scope is small enough.

So I really do you get your reasons to have any delay in merging the PRs. I would really appreciate if you could explain it, maybe as a discussion, because I am interested in better understanding people and because we all could learn from it.

Do you think you could open such discussion and explain your reasons? Then you could either look at the arguments coming from all interested people or help me to better understand your reasons and beliefs.

What do you think about it?

**Comment by quickfold** [comment]
This is so sad. Again, a very rare committed contributor is unable to work within the constraints of this project. Let_ me make a few observations.

Dimitry wrote, "My assumption is that most contributors are contributing from time to time and that they are not likely to will to be responsible for future changes."

Is there any evidence that this is true? It seems to me that most documentation has been written by very few contributors who devoted lots of time before giving up. Maybe there were many infrequent contributors in the past, but the process for contributing to documentation is SO hard that I can't imagine this happening going forward. Have there been more than 5 people in the last 10 years who have actually contributed to more than one page of documentation? Or even one page?

Dimitry, if you are unable to sufficiently respect the wishes of those who want to contribute, you will simply never have documentation for Freeplane, since you don't want to write it yourself. Perhaps you can think of giving up a modicum of control or optimization of the process as the "cost of doing business" with the type of people who are willing to write documentation.

Macmarrum says that the process wishes of the person who adds content should have some priority over the process wishes of the person who removes it. That makes 100% sense to me. If it doesn't make sense to you, so be it, but if you can't compromise on that difference of opinion, then FP will not have documentation. You don't see the reason, and you don't write documentation, and maybe there is a relationship there. If you were the type of person who did write documentation, you probably would agree with Macmarrum and me. So do you want the type of people who are willing to write documentation to work on FP or not?

Dimitry, you are a great developer, you do not write documentation at all, and you are probably a great code manager, but I hope you can see there is serious room for improvement in your ability to manage a project team that includes people with different types of personalities and mental approaches. If you want to be BDFL and want this level of control over every detail of the documentation process then you will have to write the documentation yourself, and that will not happen. If you want documentation, you will have to make some changes. It is up to you.

Please take the fact that I came back and took time to write this as a sign that I still care and wish the best for the project. I'm not even using Freeplane anymore. I gave up after working with you on it for many months. I feel like I'm watching someone unable to keep himself from destroying the potential of the thing he loves. You know (or should know) you are not the best at understanding the mental world and intentions of others, I hope you are able to learn to work better with others and that Freeplane will continue and will flourish. My sincere best wishes.

**Comment by macmarrum** [comment]
> I have been thinking about your conclusion and I do not understand what is so important to you that you prefer stepping aside to having all freedoms and opportunities.

It's hard to understand the otherness of the other, to paraphrase Carl Jung.
Some time ago I came across a TEDx Talk, which I found quite informative and funny. It helped me understand the subject a bit more: [Your personality and your brain | Scott Schwefel | TEDxBrookings](https://www.youtube.com/watch?v=8pq_tCgDkT4)

@dpolivaev you expressed the need to be productive, to avoid any wait time. While this is a perfectly valid way of looking at things and you have every right to do so, please keep in mind that there are other ways to approach projects, tasks, people or life in general.

> I want to avoid blocking the progress and waiting for the other person. It would just make everyone angry and unmotivated, the person who is waiting and the person who is pressed to respond.

You probably assumed that everyone else, except me ([I see little reason for urgency](https://github.com/freeplane/docs/pull/59#issuecomment-1193597724)), would be angry and unmotivated, because this is how you would feel. If so, it's worth to revise this assumption in the light of [Your personality and your brain | Scott Schwefel | TEDxBrookings](https://www.youtube.com/watch?v=8pq_tCgDkT4)

> Do you think you could open such discussion and explain your reasons? Then you could either look at the arguments coming from all interested people or help me to better understand your reasons and beliefs.

I've already presented my reasons. If you state concrete questions, I'll be happy to answer them.
I am fine to continue in this Conversation. Please feel free to "_write a discussion post with a reference to our discussion here just to get other opinions_", if this is what you need.

___

> Please take the fact that I came back and took time to write this as a sign that I still care and wish the best for the project.

@quickfold It's so nice of you

> I'm not even using Freeplane anymore.

I am sorry to hear that. I hope you've found a good tool to support your needs. I know there are plenty of options out there.

**Comment by dpolivaev** [comment]
@macmarrum 

> I've already presented my reasons. If you state concrete questions, I'll be happy to answer them. I am fine to continue in this Conversation.

thanks for being open to communication. Yes, I would like to ask you some more questions to understand you better.

> You probably assumed that everyone else, except me, would be angry and unmotivated, because this is how you would feel.

You are right. And, actually, I do not need to like the process you propose, it could be implemented even if we disagree because I am not participating too much in the docu development.

I would highly appreciate seeing your answers to the questions below. After having them I would like to invite other community members to share their thoughts. And at the end of the day, people who spend effort and do the work should define the process which fits them better.

Some questions.

Would you like all commits to be done through PRs?

Particularly, would you like to have  a PR in the following cases:

* adding some new documentation page
* moving some checked and improved page from the attic to the root
* removal of inconsistent information from the existing pages 
* minor editorial changes on the existing pages
* CSS style changes
* Results of work in pairing  or ensemble programming (I am going to offer an ensemble programming workshop with a focus on the scripting documentation, I suggested it during the  last community event)

How would you like to handle the PRs?

* How long should we wait for comments until the PR is merged?
* What happens in case of disagreement on parts of the PR, who should have the decision-making power?
* Who is responsible for merging the PRs?
* What happens if some PR changes parts of documentation written by different authors or modifies the structure?
* What happens if no one reacts to the PR within 7 days?
* Would it be all right if some PRs come from other branches of this repository?

Best, Dimitry

**Comment by macmarrum** [comment]
> You are right. And, actually, I do not need to like the process you propose, it could be implemented even if we disagree because I am not participating too much in the docu development.

Cool 👍 

___

> Would you like all commits to be done through PRs?

PR is important to me when content is changed and I am its author. It would also be beneficial when I change someone else's content and they comment on my PR.
I am fine with other commits going without a PR, assuming that when adding content (to existing or new pages), contributors will make sure to avoid duplication.

> Particularly, would you like to have a PR in the following cases:
> * adding some new documentation page

I am fine for such changes to go without a PR

> * moving some checked and improved page from the attic to the root

If no content is changed (e.g. only links), then I am fine for such changes to go without a PR

> * removal of inconsistent information from the existing pages

If the content's author(s) can be identified and are active, then I would like a PR to be created

> * minor editorial changes on the existing pages

I am fine with the corrections of typos, misspellings, links to go without a PR

> * CSS style changes

If the CSS author(s) or the styled content's author(s) can be identified and are active, then I would like a PR to be created

> *  Results of work in pairing or ensemble programming (I am going to offer an ensemble programming workshop with a focus on the scripting documentation, I suggested it during the last community event)

If content is changed and its author(s) can be identified and are active, then I would like the author(s) to be notified. This is normally done via a PR. But if the author(s) of changed content are part of the group (pairing or ensemble programming), I see little need for a PR as the authors are already notified.

> How would you like to handle the PRs?
> *    How long should we wait for comments until the PR is merged?

168 hours (7 days * 24h) is a reasonable number, in my opinion. People have their own lives. Creating Freeplane documentation is an after-hours voluntary activity, not a day job. I don't expect people to have time every day, but I think once a week is a reasonable expectation.

> * What happens in case of disagreement on parts of the PR, who should have the decision-making power?

This is a new point in the discussion. I need to think about it. In the meantime, maybe you could present your idea to solve this.

> * Who is responsible for merging the PRs?

I know that many projects grant collaboration rights only after people have proven to be committed (measured by regular or significant contributions). Some projects require a PR review and approval of at least 1 "trusted user" before merging can be done. In any case, by creating a PR, the submitter proposes changes and promises to see them through until the PR is closed. Therefore the submitter is ultimately responsible for merging; if no collaboration rights, then for chasing a trusted user to merge it for them. Having said that, I am fine with other people merging, as long as the changed content's author's right to comment is honored and all parties agree to go ahead

> * What happens if some PR changes parts of documentation written by different authors or modifies the structure?

If the changed content's author(s) can be identified and are active, then the submitter mentions them in PR by username (e.g. `@macmarrum`) to get their comments.
Regarding structural changes like [merging `attic` and `docs` into a single docsify instance](https://github.com/freeplane/docs/discussions/19#discussioncomment-3073047) or [splitting `attic` into `new-wiki-initiaitve` and `old-mediawiki-content`](https://github.com/freeplane/docs/discussions/19#discussioncomment-3073793), I'd say the topic falls under the project owner's purview (can decide alone or ask other members for their opinions).

> * What happens if no one reacts to the PR within 7 days?

The PR can be merged

> * Would it be all right if some PRs come from other branches of this repository?

It's fine for me, in the context of the right to comment.
Having said that, I recall the topic being discussed a few weeks ago. Arguments were presented, which lead to the agreement between @dpolivaev, @sifran-github and @macmarrum about using `forks` instead of `branches in freeplane/docs`. One of the arguments was that if a public preview of PR changes is to be made available, it can only be done from another repository (given the limitation of one GitHub-Pages instance per repo) → https://github.com/freeplane/docs/discussions/19#discussioncomment-3034553 
If we continue with the `fork` approach, I'd expect everyone to stick to it, also the people who are granted the right to create branches in freeplane/docs.

### Additional thoughts

I propose to consider an author as inactive if they fail to respond to requests for comments in at lest 2 PRs and for over 336 hours (14 days * 24h)

#### Example

Given a single author (`bee`) of changed content

* on July 1 at 11:00, PR 1 is created with `@bee`; if no comment from `bee`, it can be merged on July 8 at 11:00, after 168 hours (7 days)
* on July 3 at 21:00, PR 2 is created with `@bee`; if no comment from `bee`, it can be merged on July 10 at 21:00, after 168 hours (7 days) 
* on July 19 at 1:00, PR 3 is created with `@bee`; without comment from `bee` it can be merged on July 26 at 1:00, after 7 days; also `bee` is considered inactive: no `@bee` in future PRs until `bee` is reactivated

**Pull request merged**
