### PR TITLE
Change direct download link

### PR DESCRIPTION
**Pull request by ldmpub**
Sorry for this "very quick and short change" 🙁 linking https://sourceforge.net/projects/freeplane/files/freeplane%20stable/ is better I think.

### CODE REVIEW

**Comment by macmarrum** [comment]
@ldmpub Could you please explain why you think it is better?

**Comment by dpolivaev** [comment]
@macmarrum  IMHO the change makes sense.

**Comment by dpolivaev** [comment]
It is better because it says "All Freeplane setup files are available for download here"

**Comment by dpolivaev** [comment]
and the link should reference the directory where all setup files can be found

**Comment by ldmpub** [comment]
@macmarrum @dpolivaev thanks guys 👌.

**Comment by macmarrum** [comment]
It makes sense to me now. Thanks :pray:

**Pull request merged**
