### PR TITLE
fix theme switch symbol position

### PR DESCRIPTION
**Pull request by dpolivaev**

### CODE REVIEW

**Comment by macmarrum** [comment]
@dpolivaev I propose a different approach, i.e. to change z-order and put the sun/crescent button above the github corner. It looks better, in my opinion: https://macmarrum.github.io/freeplane-docs/

**Comment by macmarrum** [comment]
The overlap is intentional. I like it better when the buttons overlap as compared to a big gap between the sun-crescent button and the github corner.

I believe the sun-crescent button should be located out of the way, barely noticeable. Otherwise we can put it on the left, just like when the page is sized below 768 px.

**Comment by dpolivaev** [comment]
I am afraid for me the overlap looks quite wrong. You like it, and I hate it because the elements do not belong together. 

Do you have some other placement idea for the button which could please the both of us?

**Comment by macmarrum** [comment]
All clear.

I've tried other options and concluded that the location proposed by you is my choice #2. Therefore it's fine with me.

**Comment by dpolivaev** [comment]
Many thanks

**Pull request merged**
